[package]
name = "ella"
version = "0.0.1"
edition = "2021"

[build-dependencies]
bindgen = "0.69.4"

[dependencies]
clap = { version = "4.5.4", features = ["env", "derive"] }
log = "0.4.21"
log4rs = "1.3.0"
serde = { version = "1.0.197", features = ["derive"] }
libc = "0.2.153"
